### PR TITLE
Separate adding the source to MacOS and Linux

### PR DESCRIPTION
**Pull request by omarelweshy**
The command not working on Linux because of brew

### CODE REVIEW

**Comment by reubenmiller** [comment]
@omarelweshy Thanks for taking the time to create a PR.

A few months back I added a command called (`c8y cli install` and `c8y cli profile`) which will make things easier for users and document writers...I just held back on documenting it as I wanted to use it long term before I direct other users to use it.

The idea is that the user can either install the required line to all available shells using the following command:

```sh
c8y cli install
```

Or only install the profile for a given shell:

```sh
c8y cli install --shell zsh
```

The good thing is that this will be the same command regardless if people are using Windows, Linux or MacOS.

@omarelweshy What do you think about it?

**Comment by reubenmiller** [comment]
@omarelweshy Though I just noticed that you are following the "homebrew" MacOS instructions...so you shouldn't be following those instructions anyway if you're using Linux...but I do think the instructions could be more clear so that the user only sees the section that they are interested in.

**Comment by reubenmiller** [comment]
@omarelweshy I've created a new PR with the proposed changes. https://github.com/reubenmiller/go-c8y-cli/pull/415

**Comment by omarelweshy** [comment]
Hi @reubenmiller The new changes are clean and straightforward.
Thanks for your consideration.

**Pull request closed without merging**
